<?php header('Content-type: application/xml; charset=utf-8'); ?>
<?php echo '<rss version="2.0">
	<channel>
		<link>'.$protocols.'://'.$defaulturl_site.'/'.$trad['default']['index']['url'].'</link>
		<description>'.$trad['default']['index']['description'].'</description>
		<title>'.$website['info']['site']['name'].'</title>
		<item>
			<link>'.$website['info']['langs']['protocol'].'://'.$website['info']['site']['default-url'].'/'.$trad['pages']['index']['url'].'</link>
			<description>'.$trad['pages']['index']['description'].'</description>
			<title>'.$trad['pages']['index']['title'].'</title>
		</item>
		<item>
			<link>'.$website['info']['langs']['protocol'].'://'.$website['info']['site']['default-url'].'/'.$trad['pages']['support']['url'].'</link>
			<description>'.$trad['pages']['support']['description'].'</description>
			<title>'.$trad['pages']['support']['title'].'</title>
		</item>
		<item>
			<link>'.$website['info']['langs']['protocol'].'://'.$website['info']['site']['default-url'].'/'.$trad['pages']['donation']['url'].'</link>
			<description>'.$trad['pages']['donation']['description'].'</description>
			<title>'.$trad['pages']['donation']['title'].'</title>
		</item>
		<item>
			<link>'.$website['info']['langs']['protocol'].'://'.$website['info']['site']['default-url'].'/'.$trad['pages']['vote']['url'].'</link>
			<description>'.$trad['pages']['vote']['description'].'</description>
			<title>'.$trad['pages']['vote']['title'].'</title>
		</item>
		<item>
			<link>'.$website['info']['langs']['protocol'].'://'.$website['info']['site']['default-url'].'/'.$trad['pages']['shop']['url'].'</link>
			<description>'.$trad['pages']['shop']['description'].'</description>
			<title>'.$trad['pages']['shop']['title'].'</title>
		</item>
		<item>
			<link>'.$website['info']['langs']['protocol'].'://'.$website['info']['site']['default-url'].'/'.$trad['pages']['server']['url'].'</link>
			<description>'.$trad['pages']['server']['description'].'</description>
			<title>'.$trad['pages']['server']['title'].'</title>
		</item>
		<item>
			<link>'.$website['info']['langs']['protocol'].'://'.$website['info']['site']['default-url'].'/'.$trad['pages']['legal']['url'].'</link>
			<description>'.$trad['pages']['legal']['description'].'</description>
			<title>'.$trad['pages']['legal']['title'].'</title>
		</item>
		<item>
			<link>'.$website['info']['langs']['protocol'].'://'.$website['info']['site']['default-url'].'/'.$trad['pages']['author']['url'].'</link>
			<description>'.$trad['pages']['author']['description'].'</description>
			<title>'.$trad['pages']['author']['title'].'</title>
		</item>
		<item>
			<link>'.$website['info']['langs']['protocol'].'://'.$website['info']['site']['default-url'].'/'.$trad['pages']['docs']['url'].'</link>
			<description>'.$trad['pages']['docs']['description'].'</description>
			<title>'.$trad['pages']['docs']['title'].'</title>
		</item>
		<item>
			<link>'.$website['info']['langs']['protocol'].'://'.$website['info']['site']['default-url'].'/'.$trad['pages']['contact']['url'].'</link>
			<description>'.$trad['pages']['contact']['description'].'</description>
			<title>'.$trad['pages']['contact']['title'].'</title>
		</item>
		
		
	</channel>
</rss>'; ?>