<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'libphonenumber\\' => array($vendorDir . '/giggsey/libphonenumber-for-php/src'),
    'VisualAppeal\\' => array($vendorDir . '/visualappeal/php-ssllabs-api/src'),
    'Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'ReCaptcha\\' => array($vendorDir . '/google/recaptcha/src/ReCaptcha'),
    'PHPMailer\\PHPMailer\\' => array($vendorDir . '/phpmailer/phpmailer/src'),
    'Joomla\\Utilities\\' => array($vendorDir . '/joomla/utilities/src'),
    'Joomla\\String\\' => array($vendorDir . '/joomla/string/src'),
    'Icamys\\SitemapGenerator\\' => array($vendorDir . '/icamys/php-sitemap-generator/src'),
    'Giggsey\\Locale\\' => array($vendorDir . '/giggsey/locale/src'),
);
